/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agiota;

import classe.Cliente;
import conexoes.MySQL;
import javax.swing.JOptionPane;

/**
 *
 * @author limal
 */
public class AprovacaoEmprestimo extends javax.swing.JFrame {
    MySQL conectar = new MySQL();
    Cliente novoCliente = new Cliente ();
    /**
     * Creates new form novaSenha
     */
    public AprovacaoEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtemailAntigo2 = new javax.swing.JTextField();
        txtEmrpestimo1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JButton();
        jreprovar = new javax.swing.JButton();
        txtEmrpestimo = new javax.swing.JTextField();
        btnCadastroCadastro2 = new javax.swing.JButton();
        txtEmrpestimo2 = new javax.swing.JTextField();
        txtEmrpestimo3 = new javax.swing.JTextField();
        txtEmrpestimo4 = new javax.swing.JTextField();
        txtEmrpestimo5 = new javax.swing.JTextField();
        txtEmrpestimo6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmrpestimo7 = new javax.swing.JTextField();
        txtEmrpestimo8 = new javax.swing.JTextField();
        txtEmrpestimo9 = new javax.swing.JTextField();
        txtEmrpestimo10 = new javax.swing.JTextField();
        txtEmrpestimo11 = new javax.swing.JTextField();
        txtEmrpestimo12 = new javax.swing.JTextField();
        japrovar = new javax.swing.JButton();
        jreprovar1 = new javax.swing.JButton();
        japrovar1 = new javax.swing.JButton();
        jreprovar2 = new javax.swing.JButton();
        japrovar2 = new javax.swing.JButton();
        jreprovar3 = new javax.swing.JButton();
        japrovar3 = new javax.swing.JButton();
        jreprovar4 = new javax.swing.JButton();
        japrovar4 = new javax.swing.JButton();
        jreprovar5 = new javax.swing.JButton();
        japrovar5 = new javax.swing.JButton();

        txtemailAntigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailAntigo2ActionPerformed(evt);
            }
        });

        txtEmrpestimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Valor");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Aprovação Emprestimo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/binoculars.png"))); // NOI18N
        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jreprovar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jreprovar.setText("Negar");
        jreprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreprovarActionPerformed(evt);
            }
        });

        txtEmrpestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimoActionPerformed(evt);
            }
        });

        btnCadastroCadastro2.setBackground(new java.awt.Color(255, 0, 51));
        btnCadastroCadastro2.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastroCadastro2.setText("Cancelar");
        btnCadastroCadastro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroCadastro2ActionPerformed(evt);
            }
        });

        txtEmrpestimo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo2ActionPerformed(evt);
            }
        });

        txtEmrpestimo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo3ActionPerformed(evt);
            }
        });

        txtEmrpestimo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo4ActionPerformed(evt);
            }
        });

        txtEmrpestimo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo5ActionPerformed(evt);
            }
        });

        txtEmrpestimo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo6ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        txtEmrpestimo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo7ActionPerformed(evt);
            }
        });

        txtEmrpestimo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo8ActionPerformed(evt);
            }
        });

        txtEmrpestimo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo9ActionPerformed(evt);
            }
        });

        txtEmrpestimo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo10ActionPerformed(evt);
            }
        });

        txtEmrpestimo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo11ActionPerformed(evt);
            }
        });

        txtEmrpestimo12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrpestimo12ActionPerformed(evt);
            }
        });

        japrovar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/updated.png"))); // NOI18N
        japrovar.setText("Aprovar");
        japrovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japrovarActionPerformed(evt);
            }
        });

        jreprovar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jreprovar1.setText("Negar");
        jreprovar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreprovar1ActionPerformed(evt);
            }
        });

        japrovar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/updated.png"))); // NOI18N
        japrovar1.setText("Aprovar");
        japrovar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japrovar1ActionPerformed(evt);
            }
        });

        jreprovar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jreprovar2.setText("Negar");
        jreprovar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreprovar2ActionPerformed(evt);
            }
        });

        japrovar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/updated.png"))); // NOI18N
        japrovar2.setText("Aprovar");
        japrovar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japrovar2ActionPerformed(evt);
            }
        });

        jreprovar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jreprovar3.setText("Negar");
        jreprovar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreprovar3ActionPerformed(evt);
            }
        });

        japrovar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/updated.png"))); // NOI18N
        japrovar3.setText("Aprovar");
        japrovar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japrovar3ActionPerformed(evt);
            }
        });

        jreprovar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jreprovar4.setText("Negar");
        jreprovar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreprovar4ActionPerformed(evt);
            }
        });

        japrovar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/updated.png"))); // NOI18N
        japrovar4.setText("Aprovar");
        japrovar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japrovar4ActionPerformed(evt);
            }
        });

        jreprovar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        jreprovar5.setText("Negar");
        jreprovar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreprovar5ActionPerformed(evt);
            }
        });

        japrovar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/updated.png"))); // NOI18N
        japrovar5.setText("Aprovar");
        japrovar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japrovar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastroCadastro2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmrpestimo6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(txtEmrpestimo5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmrpestimo4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmrpestimo3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmrpestimo2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmrpestimo))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmrpestimo12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txtEmrpestimo11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmrpestimo10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmrpestimo9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmrpestimo8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmrpestimo7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jreprovar4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(japrovar4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jreprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(japrovar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jreprovar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(japrovar1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jreprovar2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(japrovar2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jreprovar3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(japrovar3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jreprovar5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(japrovar5)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmrpestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmrpestimo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreprovar)
                    .addComponent(japrovar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmrpestimo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmrpestimo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreprovar1)
                    .addComponent(japrovar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmrpestimo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmrpestimo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreprovar2)
                    .addComponent(japrovar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmrpestimo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmrpestimo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreprovar3)
                    .addComponent(japrovar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmrpestimo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmrpestimo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreprovar4)
                    .addComponent(japrovar4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmrpestimo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmrpestimo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreprovar5)
                    .addComponent(japrovar5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuscar)
                    .addComponent(btnCadastroCadastro2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        

    public void atualizarEmail(Cliente novoCliente){
        this.conectar.conectaBanco();
        
        String consultaEmail = this.txtEmrpestimo.getText();
        
        try{
            var atualizaCpf = "UPDATE cadastroclientes SET "
                    + "email = '" + txtEmrpestimo.getText() + "' "
                    + " WHERE "
                    + " email = '" + consultaEmail + "';"
                    ;
            this.conectar.updateSQL (atualizaCpf);
            System.out.println(atualizaCpf);
            
            if(novoCliente.getNome() == ""){
                JOptionPane.showMessageDialog(null, "Erro não Buscar E-mail");
            }         
        } catch(Exception e) {
            System.out.println("Erro ao Atualizar Cliente"+ e.getMessage());
            JOptionPane.showMessageDialog (null, "Erro ao buscar Email");
        
        } finally {
            txtEmrpestimo.setText(novoCliente.getSenha());
          
            
        }
    }
    
    private void txtEmrpestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimoActionPerformed

    private void txtemailAntigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailAntigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailAntigo2ActionPerformed

    private void jreprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreprovarActionPerformed
        // TODO add your handling code here:
        novoCliente.LimparCliente();
        this.txtEmrpestimo.setText("");
      
    }//GEN-LAST:event_jreprovarActionPerformed

    private void btnCadastroCadastro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroCadastro2ActionPerformed
        // TODO add your handling code here:
        new DividaAgiota().setVisible(true);
        AprovacaoEmprestimo.this.dispose();
    }//GEN-LAST:event_btnCadastroCadastro2ActionPerformed

    private void txtEmrpestimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo1ActionPerformed

    private void txtEmrpestimo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo2ActionPerformed

    private void txtEmrpestimo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo3ActionPerformed

    private void txtEmrpestimo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo4ActionPerformed

    private void txtEmrpestimo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo5ActionPerformed

    private void txtEmrpestimo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo6ActionPerformed

    private void txtEmrpestimo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo7ActionPerformed

    private void txtEmrpestimo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo8ActionPerformed

    private void txtEmrpestimo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo9ActionPerformed

    private void txtEmrpestimo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo10ActionPerformed

    private void txtEmrpestimo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo11ActionPerformed

    private void txtEmrpestimo12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrpestimo12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmrpestimo12ActionPerformed

    private void japrovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japrovarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japrovarActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // TODO add your handling code here:
        atualizarEmail(novoCliente);
        new InformacoesPessoais().setVisible(true);
        AprovacaoEmprestimo.this.dispose();
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jreprovar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreprovar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jreprovar1ActionPerformed

    private void japrovar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japrovar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japrovar1ActionPerformed

    private void jreprovar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreprovar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jreprovar2ActionPerformed

    private void japrovar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japrovar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japrovar2ActionPerformed

    private void jreprovar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreprovar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jreprovar3ActionPerformed

    private void japrovar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japrovar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japrovar3ActionPerformed

    private void jreprovar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreprovar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jreprovar4ActionPerformed

    private void japrovar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japrovar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japrovar4ActionPerformed

    private void jreprovar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreprovar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jreprovar5ActionPerformed

    private void japrovar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japrovar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japrovar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AprovacaoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AprovacaoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AprovacaoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AprovacaoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AprovacaoEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroCadastro2;
    private javax.swing.JButton jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton japrovar;
    private javax.swing.JButton japrovar1;
    private javax.swing.JButton japrovar2;
    private javax.swing.JButton japrovar3;
    private javax.swing.JButton japrovar4;
    private javax.swing.JButton japrovar5;
    private javax.swing.JButton jreprovar;
    private javax.swing.JButton jreprovar1;
    private javax.swing.JButton jreprovar2;
    private javax.swing.JButton jreprovar3;
    private javax.swing.JButton jreprovar4;
    private javax.swing.JButton jreprovar5;
    private javax.swing.JTextField txtEmrpestimo;
    private javax.swing.JTextField txtEmrpestimo1;
    private javax.swing.JTextField txtEmrpestimo10;
    private javax.swing.JTextField txtEmrpestimo11;
    private javax.swing.JTextField txtEmrpestimo12;
    private javax.swing.JTextField txtEmrpestimo2;
    private javax.swing.JTextField txtEmrpestimo3;
    private javax.swing.JTextField txtEmrpestimo4;
    private javax.swing.JTextField txtEmrpestimo5;
    private javax.swing.JTextField txtEmrpestimo6;
    private javax.swing.JTextField txtEmrpestimo7;
    private javax.swing.JTextField txtEmrpestimo8;
    private javax.swing.JTextField txtEmrpestimo9;
    private javax.swing.JTextField txtemailAntigo2;
    // End of variables declaration//GEN-END:variables

}
