package janelas;

import conexoes.MySQL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static classe.Gerenciador.idLogado;


public class ConsultaDevedor extends javax.swing.JFrame {
    MySQL conectar = new MySQL();

    public ConsultaDevedor() {
        initComponents();
        buscarDividas();
    }
    
    public void buscarDividas(){
        String columnNames[] = {"Credor", "Valor Atual", "Valor Proximo Mês", "Status"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        try{
            this.conectar.conectaBanco();
            String query = "SELECT " +
                "pessoa.nome, " +
                "divida.valorAtual, " +
                "divida.valorProMes, " +
                "Situacao.nome " +
                "FROM divida " +
                "JOIN pessoa ON pessoa.Id = divida.agiotaId " +
                "JOIN situacao ON situacao.id = divida.situacaoDivida " +
                "WHERE divida.devedorId = " + idLogado;
            this.conectar.executarSQL(query);
            while (this.conectar.getResultSet().next()) {
                model.addRow(new String[]{
                    this.conectar.getResultSet().getString(1),
                    String.valueOf(this.conectar.getResultSet().getDouble(2)),
                    String.valueOf(this.conectar.getResultSet().getDouble(3)),
                    this.conectar.getResultSet().getString(4)
                });
            }
        } catch (Exception e) {
            System.out.println("Erro ao listar dívidas! " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao listar dívidas!");
            
        } finally {
            this.conectar.fechaBanco();
        }
        
        tConsulta.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        spLista = new javax.swing.JScrollPane();
        tConsulta = new javax.swing.JTable();
        lblConsulta1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Divida");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Credor", "Valor Atual", "Valor Proximo mês", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tConsulta.setRowHeight(25);
        tConsulta.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                tConsultaComponentRemoved(evt);
            }
        });
        spLista.setViewportView(tConsulta);

        jPanel2.add(spLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 162, 1028, 384));

        lblConsulta1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblConsulta1.setForeground(new java.awt.Color(220, 174, 50));
        lblConsulta1.setText("Dívidas Ativas");
        jPanel2.add(lblConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(255, 51, 51));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botaovoltar.png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 110, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 174, 50));
        jLabel2.setText("Olá, Endividado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/consultadevedor.png"))); // NOI18N
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoMouseEntered(evt);
            }
        });
        jPanel2.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1060, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tConsultaComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tConsultaComponentRemoved
       
    }//GEN-LAST:event_tConsultaComponentRemoved

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new MenuDevedor().setVisible(true);
        ConsultaDevedor.this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogoMouseClicked

    private void lblLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaDevedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaDevedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaDevedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaDevedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaDevedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConsulta1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JScrollPane spLista;
    private javax.swing.JTable tConsulta;
    // End of variables declaration//GEN-END:variables
}
