package janelas;

import static classe.Gerenciador.limparDados;
import conexoes.MySQL;
import javax.swing.JOptionPane;
import static classe.Gerenciador.usuarioLogado;

public class MenuDevedor extends javax.swing.JFrame {
    MySQL conectar = new MySQL();

    public MenuDevedor() {
        initComponents();
        this.lblOla.setText("Olá, " + usuarioLogado.getNome());
        buscarDividaTotal();
    }
    
    public void buscarDividaTotal(){
        this.conectar.conectaBanco();
        try{
            String query = "SELECT "
                    + "SUM(valorAtual),"
                    + "COUNT(1) "
                    + "FROM divida "
                    + "WHERE devedorId = " + usuarioLogado.getId();
            
            this.conectar.executarSQL (query);
            
            while (this.conectar.getResultSet().next()) {
                this.lblDividaTotalValor.setText("R$ " + this.conectar.getResultSet().getDouble(1));
                this.lblTotalAgiotas.setText("" + this.conectar.getResultSet().getInt(2));
            }
        } catch (Exception e) {
            System.out.println("Erro ao buscar dívidas! " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar dívidas!");
            
        } finally {
            this.conectar.fechaBanco();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInicial = new javax.swing.JPanel();
        pDivida = new javax.swing.JPanel();
        lblDividaTotalValor = new javax.swing.JLabel();
        btnAtualConsulta = new javax.swing.JButton();
        btnAtualDados = new javax.swing.JButton();
        btnAtualDados1 = new javax.swing.JButton();
        lblVoceEstaDevendo = new javax.swing.JLabel();
        lblDividaAtual = new javax.swing.JLabel();
        lblTotalAgiotas = new javax.swing.JLabel();
        lblAgiotas = new javax.swing.JLabel();
        lblOla = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pInicial.setBackground(new java.awt.Color(0, 0, 0));
        pInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pDivida.setBackground(new java.awt.Color(220, 174, 50));

        lblDividaTotalValor.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        lblDividaTotalValor.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pDividaLayout = new javax.swing.GroupLayout(pDivida);
        pDivida.setLayout(pDividaLayout);
        pDividaLayout.setHorizontalGroup(
            pDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDividaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDividaTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDividaLayout.setVerticalGroup(
            pDividaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDividaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDividaTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pInicial.add(pDivida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 720, -1));

        btnAtualConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/consulat2.png"))); // NOI18N
        btnAtualConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualConsultaActionPerformed(evt);
            }
        });
        pInicial.add(btnAtualConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 220, 70));

        btnAtualDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dados2.png"))); // NOI18N
        btnAtualDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualDadosActionPerformed(evt);
            }
        });
        pInicial.add(btnAtualDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 130, 40));

        btnAtualDados1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoff2.png"))); // NOI18N
        btnAtualDados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualDados1ActionPerformed(evt);
            }
        });
        pInicial.add(btnAtualDados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 110, 40));

        lblVoceEstaDevendo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblVoceEstaDevendo.setForeground(new java.awt.Color(220, 174, 50));
        lblVoceEstaDevendo.setText("Você está devendo para");
        pInicial.add(lblVoceEstaDevendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        lblDividaAtual.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDividaAtual.setForeground(new java.awt.Color(220, 174, 50));
        lblDividaAtual.setText("Dívida atual total:");
        pInicial.add(lblDividaAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        lblTotalAgiotas.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblTotalAgiotas.setForeground(new java.awt.Color(255, 102, 102));
        pInicial.add(lblTotalAgiotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 45, 16));

        lblAgiotas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAgiotas.setForeground(new java.awt.Color(220, 174, 50));
        lblAgiotas.setText("agiotas.");
        pInicial.add(lblAgiotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        lblOla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOla.setForeground(new java.awt.Color(220, 174, 50));
        lblOla.setText("Olá, Devedor");
        lblOla.setToolTipText("");
        pInicial.add(lblOla, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 30));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menudevedor.png"))); // NOI18N
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoMouseEntered(evt);
            }
        });
        pInicial.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1080, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualDadosActionPerformed
        new InformacoesPessoais().setVisible(true);
        MenuDevedor.this.dispose();
    }//GEN-LAST:event_btnAtualDadosActionPerformed

    private void btnAtualConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualConsultaActionPerformed
        // TODO add your handling code here:
        new ConsultaDevedor().setVisible(true);
        MenuDevedor.this.dispose();
    }//GEN-LAST:event_btnAtualConsultaActionPerformed

    private void btnAtualDados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualDados1ActionPerformed
        new Login().setVisible(true);
        limparDados();
        MenuDevedor.this.dispose();
    }//GEN-LAST:event_btnAtualDados1ActionPerformed

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogoMouseClicked

    private void lblLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDevedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDevedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDevedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDevedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDevedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualConsulta;
    private javax.swing.JButton btnAtualDados;
    private javax.swing.JButton btnAtualDados1;
    private javax.swing.JLabel lblAgiotas;
    private javax.swing.JLabel lblDividaAtual;
    private javax.swing.JLabel lblDividaTotalValor;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOla;
    private javax.swing.JLabel lblTotalAgiotas;
    private javax.swing.JLabel lblVoceEstaDevendo;
    private javax.swing.JPanel pDivida;
    private javax.swing.JPanel pInicial;
    // End of variables declaration//GEN-END:variables
}
