package janelas;

import static classe.Gerenciador.idLogado;
import classe.Pessoa;
import conexoes.MySQL;
import javax.swing.JOptionPane;

public class novaSenha extends javax.swing.JFrame {
    MySQL conectar = new MySQL();
    Pessoa novoCliente = new Pessoa();

    public novaSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        lblNovaSenha = new javax.swing.JLabel();
        pwdTrocaSenha = new javax.swing.JPasswordField();
        lblRepSenha = new javax.swing.JLabel();
        pwdRepitaSenha = new javax.swing.JPasswordField();
        lblSenhaAnt = new javax.swing.JLabel();
        pwdSenhaAntiga = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Senha");

        pPrincipal.setBackground(new java.awt.Color(255, 102, 51));
        pPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNovaSenha.setBackground(new java.awt.Color(0, 0, 0));
        lblNovaSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNovaSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblNovaSenha.setText("Nova senha");
        pPrincipal.add(lblNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 100, -1));
        pPrincipal.add(pwdTrocaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 129, -1));

        lblRepSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRepSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblRepSenha.setText("Repetir senha");
        pPrincipal.add(lblRepSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));
        pPrincipal.add(pwdRepitaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 129, -1));

        lblSenhaAnt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSenhaAnt.setForeground(new java.awt.Color(255, 255, 255));
        lblSenhaAnt.setText("Senha Antiga");
        pPrincipal.add(lblSenhaAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));
        pPrincipal.add(pwdSenhaAntiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 129, -1));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        pPrincipal.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(220, 174, 50));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        lblBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/novasenha.png"))); // NOI18N
        pPrincipal.add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new InformacoesPessoais().setVisible(true);
        novaSenha.this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        novoCliente.limparDados();
        this.pwdSenhaAntiga.setText("");
        this.pwdTrocaSenha.setText("");
        this.pwdRepitaSenha.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        atualizarSenha(novoCliente);
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void atualizarSenha(Pessoa novoCliente){
        this.conectar.conectaBanco();
        
        String consultaSenha = this.pwdSenhaAntiga.getText();
        
        try{
            String atualizaCpf = "UPDATE pessoa SET "
                    + "senha = '" + pwdTrocaSenha.getText() + "' "
                    + " WHERE id = " + idLogado
                    + " AND senha = '" + consultaSenha + "';";
            this.conectar.updateSQL(atualizaCpf);
            JOptionPane.showMessageDialog (null, "Senha atualizada com sucesso!");
            new InformacoesPessoais().setVisible(true);
            novaSenha.this.dispose();
        } catch(Exception e) {
            System.out.println("Erro ao Atualizar Cliente"+ e.getMessage());
            JOptionPane.showMessageDialog (null, "Erro ao buscar Senha");
        } finally {
            this.conectar.fechaBanco();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(novaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(novaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(novaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(novaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new novaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblNovaSenha;
    private javax.swing.JLabel lblRepSenha;
    private javax.swing.JLabel lblSenhaAnt;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JPasswordField pwdRepitaSenha;
    private javax.swing.JPasswordField pwdSenhaAntiga;
    private javax.swing.JPasswordField pwdTrocaSenha;
    // End of variables declaration//GEN-END:variables

}
